# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            IP
tagline:          'Ioannis Poulakas - Software Developer'
description:      'Software / Web / iOS Developer'
url:              http://giannisp.github.io
baseurl:          /

author:
  name:           'Ioannis Poulakas'
  url:            https://github.com/giannisp

paginate:         5

# Custom
subtitle:         Ioannis Poulakas

# Gems
gems:             [jekyll-paginate, jekyll-gist]
